#!/usr/bin/env bash

source ~/.python/iei/bin/activate

#env WATCHFILES_FORCE_POLLING=true uvicorn  --host=0.0.0.0  --reload image_embedding_indexer_api:app

#export IEI_PATH=./data/home_photos.iei
#export IEI_PATH="./data/image_embedding_indexes"
# export IEI_USER_AGENT="Clip Embedding Calculator/0.01 (https://github.com/ramayer/wikipedia_in_spark; ramayer+git@gmail.com) generic-library/0.0"

if [ x"${IEI_PATH}" == "x" ]; then 
     echo "You probably want to setenv IEI_PATH and IEI_USER_AGENT"
     exit
else
     echo using $IEI_PATH
fi

# 1 worker process for ML to not run out of GPU ram
uvicorn  --host=0.0.0.0 --reload image_embedding_indexer_api:app --port=8000 &
# 8 worker process for serving thumbnails
uvicorn  --host=0.0.0.0 --reload image_embedding_indexer_api:app --port=8001 --workers=8 &
wait




