#!/usr/bin/env python

import fire
import image_embedding_indexer

iei=image_embedding_indexer.ImageEmbeddingIndexer(device='cpu')

def reprocess(*img_ids):
    for img_id in img_ids:
        print(iei.get_metadata(img_id))
        print(iei.get_img_data(img_id))
        print(iei.reprocess_image(img_id))

if __name__ == '__main__':
    fire.Fire(reprocess)
